services:
  redis:
    build: ./redis
    container_name: redis.g
    hostname: redis.g
    volumes:
      - ./redis/working_dir/:/root/working_dir
    restart: unless-stopped
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
