services:
  dev_env:
    build:
      context: .
      args:
        ENABLE_PYTHON: true
        ENABLE_CPP: true
        GITHUB_USERNAME: "BorisKaryshev"
        GITHUB_EMAIL: "boris.karyshev@gmail.com"

    container_name: dev_env.g
    hostname: dev_env.g
    network_mode: bridge
    restart: no
    dns:
      - 192.168.1.12
      # Ip of host machine with running dnsmasq and
      # deameon, which writes container IPs to /etc/hosts
      # So there is access from this container to other containers by their names
      - 77.88.8.8
      - 77.88.8.1

    # github auth configuring
    secrets:
      - github_ssh_token
secrets:
   github_ssh_token:
     file: /home/b-karyshev/.ssh/github_auth
